using System;
using Crestron.SimplSharp;                          				// For Basic SIMPL# Classes
using Crestron.SimplSharpPro;                       				// For Basic SIMPL#Pro classes

namespace SspCompanyVideoDisplayEthernet
{
    public class DataFileString
    {
        public const string Json = "{\r\n  \"CrestronSerialDeviceApi\": {\r\n    \"GeneralInformation\": {\r\n      \"DeviceType\": \"Display\",\r\n      \"Manufacturer\": \"SspCompany\",\r\n      \"DeviceModel\": \"VideoDisplay\"\r\n    },\r\n    \"Api\": {\r\n      \"Communication\": {\r\n        \"Protocol\": 0,\r\n        \"Baud\": 1024,\r\n        \"Parity\": 1,\r\n        \"HwHandshake\": 0,\r\n        \"SwHandshake\": 0,\r\n        \"ResponseTimeout\": 5000,\r\n        \"DataBits\": 8,\r\n        \"StopBits\": 1,\r\n        \"Port\": 23,\r\n        \"WarmUpTime\": 10,\r\n        \"CoolDownTime\": 5,\r\n        \"WaitForResponse\": false,\r\n        \"TimeBetweenCommands\": 100,\r\n        \"EnableAutoPolling\": true,\r\n        \"EnableAutoReconnect\": true\r\n      },\r\n      \"Commands\": {\r\n        \"PowerOn\": {\r\n          \"StandardCommand\": 161,\r\n          \"Command\": \"Power On\",\r\n          \"Parameters\": []\r\n        },\r\n        \"PowerOff\": {\r\n          \"StandardCommand\": 160,\r\n          \"Command\": \"Power Off\",\r\n          \"Parameters\": []\r\n        },\r\n        \"Hdmi1\": {\r\n          \"StandardCommand\": 10,\r\n          \"Command\": \"HDMI Input 1\",\r\n          \"Parameters\": []\r\n        },\r\n        \"Hdmi2\": {\r\n          \"StandardCommand\": 12,\r\n          \"Command\": \"HDMI Input 2\",\r\n          \"Parameters\": []\r\n        },\r\n        \"VolPlus\": {\r\n          \"StandardCommand\": 168,\r\n          \"Command\": \"Volume Level Up\",\r\n          \"Parameters\": []\r\n        },\r\n        \"VolMinus\": {\r\n          \"StandardCommand\": 167,\r\n          \"Command\": \"Volume Level Down\",\r\n          \"Parameters\": []\r\n        },\r\n        \"Mute\": {\r\n          \"StandardCommand\": 136,\r\n          \"Command\": \"Volume Mute\",\r\n          \"Parameters\": []\r\n        }\r\n      },\r\n      \"Feedback\": {\r\n        \"CommandAckNak\": {\r\n          \"Ack\": \"\",\r\n          \"Nak\": \"\"\r\n        },\r\n        \"Header\": \"\",\r\n        \"PowerFeedback\": {\r\n          \"Feedback\": {\r\n            \"On\": \"Power is On\",\r\n            \"Off\": \"Power is Off\"\r\n          },\r\n          \"GroupHeader\": \"\"\r\n        },\r\n        \"MuteFeedback\": {\r\n          \"Feedback\": {\r\n            \"On\": \"Volume Mute is On\",\r\n            \"Off\": \"Volume Mute is Off\"\r\n          },\r\n          \"GroupHeader\": \"\"\r\n        },\r\n        \"InputFeedback\": {\r\n          \"GroupHeader\": \"\",\r\n          \"Feedback\": [\r\n            {\r\n              \"InputType\": 10,\r\n              \"Feedback\": \"HDMI is Input 1\"\r\n            },\r\n            {\r\n              \"InputType\": 12,\r\n              \"Feedback\": \"HDMI is Input 2\"\r\n            }\r\n          ]\r\n        },\r\n        \"VolumeFeedback\": {\r\n          \"GroupHeader\": \"Volume Level is\"\r\n        }\r\n      }\r\n    }\r\n  }\r\n}";
    }

}

